### ISSUE TITLE
Other Mobile Phone

### ISSUE THREAD

**Issue by Qbart1337** [hankes-garden/capacitive_screen#1]
Hi,

i liked your idea and its useful for my project. I want to add some algorithm to it and get infomation about the direction of the fingers. If i do this on a new mobile phone like S6+ this will not work i guess?
Other screen driver?
But when i modify the S6 screen driver like you did, will this working out with your cap_reader,py too?
Can you help me how you get it done?

**Comment by hankes-garden** [comment]
Hi,

For different mobile devices, you may need to find the source code of the corresponding driver.

As long as your OS is android, the script should work.  However, the basic idea is that, the driver is modified to save the data you wanted in a specific file in kernel mode, and the script can read the data from this file in user mode. You can write your code in a similar way.
