### ISSUE TITLE
About the amplitude_log file

### ISSUE THREAD

**Issue by Qbart1337** [hankes-garden/capacitive_screen#2]
Hi Yang,

i know its a long time since you worked on this, but is got some questions which would push me.
I got my set-up with i9100 as well. 
Right now ia about the recreate your app to read out the files too. But i cant get it how the logfile will be refreshed and why there are only 66 values in there.
I tried to study the the atmel Datasheet to get more informations. Didnt help.
The way i undertstood the documentations would be requiere to have 224 values. 
Am i wrong ?? :/

Stefan (Student, Germany)

**Comment by hankes-garden** [comment]
Hi, Stefan,

Thanks for being interested in this code. Here is some information may help you.

>1. How is the logfile refreshed?

 In the screen driver (mxt224_u1.c), I implemented a delayed work queue, which will get the raw capacitance value and write to the logfile with a fix refresh rate(ref. get_raw_data() function).

>2. why are there only 66 values?

For the simplicy of test, I only print the first page of data (There are 4 pages in total), you can change it in the screen driver (ref. read_all_delta_data_ex() function in mxt224_u1.c)
